import type { MigrationPlan, MigrationPlanPhase, MigrationAction, MigrationRequirements } from './plan.js';
import type { ResourceType } from '../resources/resource.js';

/**
 * CloudFormation Template Generator — FALLBACK / SCAFFOLD path.
 *
 * ⚠️ This produces SCAFFOLD templates (structure + placeholders) from the plan.
 * For FAITHFUL templates that reproduce the real resource config, use
 * `iac-generator.ts` (generateFaithfulTemplate) — that is the PRIMARY path,
 * backed by the AWS CloudFormation IaC Generator + AWS Config.
 *
 * This generator remains useful for:
 *   - Resource types NOT supported by the IaC Generator (isIacGeneratorSupported=false)
 *   - Offline/no-credentials scaffolding to review the phase structure
 *   - A skeleton to hand-edit when the real config is not needed
 *
 * Templates are strings (YAML) — never executed. Validation runs separately.
 */

// CloudFormation resource type mapping
const RESOURCE_TYPE_TO_CFN: Partial<Record<ResourceType, string>> = {
  'AWS::EC2::VPC': 'AWS::EC2::VPC',
  'AWS::EC2::Subnet': 'AWS::EC2::Subnet',
  'AWS::EC2::SecurityGroup': 'AWS::EC2::SecurityGroup',
  'AWS::EC2::Instance': 'AWS::EC2::Instance',
  'AWS::EC2::InternetGateway': 'AWS::EC2::InternetGateway',
  'AWS::EC2::NatGateway': 'AWS::EC2::NatGateway',
  'AWS::EC2::RouteTable': 'AWS::EC2::RouteTable',
  'AWS::EC2::Volume': 'AWS::EC2::Volume',
  'AWS::EC2::EIP': 'AWS::EC2::EIP',
  'AWS::ECS::Cluster': 'AWS::ECS::Cluster',
  'AWS::ECS::Service': 'AWS::ECS::Service',
  'AWS::ElasticLoadBalancingV2::LoadBalancer': 'AWS::ElasticLoadBalancingV2::LoadBalancer',
  'AWS::ElasticLoadBalancingV2::TargetGroup': 'AWS::ElasticLoadBalancingV2::TargetGroup',
  'AWS::RDS::DBInstance': 'AWS::RDS::DBInstance',
  'AWS::S3::Bucket': 'AWS::S3::Bucket',
  'AWS::Lambda::Function': 'AWS::Lambda::Function',
  'AWS::IAM::Role': 'AWS::IAM::Role',
  'AWS::DynamoDB::Table': 'AWS::DynamoDB::Table',
  'AWS::SQS::Queue': 'AWS::SQS::Queue',
  'AWS::SNS::Topic': 'AWS::SNS::Topic',
  'AWS::ECR::Repository': 'AWS::ECR::Repository',
};

export interface GeneratedTemplate {
  stackName: string;
  templatePath: string;
  yaml: string;
}

/**
 * Generate CloudFormation templates for each phase in the plan.
 */
export function generateCfnTemplates(plan: MigrationPlan): GeneratedTemplate[] {
  const templates: GeneratedTemplate[] = [];

  for (const phase of plan.phases) {
    for (const stack of phase.cfnStacks) {
      const yaml = generatePhaseTemplate(phase, plan.requirements);
      templates.push({
        stackName: stack.stackName,
        templatePath: stack.templatePath,
        yaml,
      });
    }
  }

  return templates;
}

function generatePhaseTemplate(
  phase: MigrationPlanPhase,
  requirements: MigrationRequirements
): string {
  const resources: string[] = [];
  const outputs: string[] = [];

  for (const action of phase.actions) {
    if (action.actionType === 'CUTOVER_DNS' || action.actionType === 'DECOMMISSION_SOURCE') {
      continue; // These are manual, not CFN-managed
    }
    if (action.actionType === 'VALIDATE') {
      continue; // Validation is not a CFN resource
    }

    const cfnResource = generateResourceBlock(action, requirements);
    if (cfnResource) {
      resources.push(cfnResource);
      outputs.push(generateOutputBlock(action));
    }
  }

  // If phase has no CFN-manageable resources, produce a comment-only template
  if (resources.length === 0) {
    return generateManualPhaseTemplate(phase, requirements);
  }

  return `AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  Migration Phase ${phase.order}: ${phase.name}
  Generated by aws-migration-mvp planner.
  ${phase.actions.length} actions, estimated ${phase.estimatedDurationMinutes} minutes.

Parameters:
  Environment:
    Type: String
    Default: migration
    Description: Deployment environment tag

  SourceRegion:
    Type: String
    Default: ${requirements.sourceRegion}
    Description: Source AWS region

  TargetVpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID in the target region (create networking phase first)

  TargetSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Subnet IDs in the target VPC

Resources:
${resources.join('\n\n')}

Outputs:
${outputs.join('\n\n')}
`;
}

function generateResourceBlock(action: MigrationAction, requirements: MigrationRequirements): string | null {
  const logicalId = sanitizeLogicalId(action.resourceName || action.resourceId);
  const cfnType = RESOURCE_TYPE_TO_CFN[action.resourceType];

  if (!cfnType) return null;

  switch (action.resourceType) {
    case 'AWS::EC2::VPC':
      return generateVpcResource(logicalId, action);
    case 'AWS::EC2::Subnet':
      return generateSubnetResource(logicalId, action);
    case 'AWS::EC2::SecurityGroup':
      return generateSecurityGroupResource(logicalId, action);
    case 'AWS::EC2::Instance':
      return generateEc2Resource(logicalId, action);
    case 'AWS::RDS::DBInstance':
      return generateRdsResource(logicalId, action, requirements);
    case 'AWS::S3::Bucket':
      return generateS3Resource(logicalId, action);
    case 'AWS::Lambda::Function':
      return generateLambdaResource(logicalId, action);
    case 'AWS::DynamoDB::Table':
      return generateDynamoDbResource(logicalId, action);
    case 'AWS::ECS::Cluster':
      return generateEcsClusterResource(logicalId, action);
    case 'AWS::SQS::Queue':
      return generateSqsResource(logicalId, action);
    case 'AWS::SNS::Topic':
      return generateSnsResource(logicalId, action);
    default:
      return generateGenericResource(logicalId, action, cfnType);
  }
}

// ── Resource generators ─────────────────────────────────────────────────────

function generateVpcResource(id: string, action: MigrationAction): string {
  return `  ${id}:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: '10.0.0.0/16' # TODO: adjust CIDR for target
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: ${action.resourceName}-migrated
        - Key: MigrationSource
          Value: ${action.resourceId}
        - Key: Environment
          Value: !Ref Environment`;
}

function generateSubnetResource(id: string, action: MigrationAction): string {
  return `  ${id}:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref TargetVpcId
      CidrBlock: '10.0.1.0/24' # TODO: assign from target CIDR plan
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: ${action.resourceName}-migrated
        - Key: MigrationSource
          Value: ${action.resourceId}`;
}

function generateSecurityGroupResource(id: string, action: MigrationAction): string {
  return `  ${id}:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: 'Migrated from ${action.resourceName} (${action.resourceId})'
      VpcId: !Ref TargetVpcId
      Tags:
        - Key: Name
          Value: ${action.resourceName}-migrated
        - Key: MigrationSource
          Value: ${action.resourceId}
      # TODO: Copy ingress/egress rules from source security group`;
}

function generateEc2Resource(id: string, action: MigrationAction): string {
  return `  ${id}:
    Type: AWS::EC2::Instance
    Properties:
      # AMI must be copied to target region first (pre-flight check)
      ImageId: 'ami-PLACEHOLDER' # TODO: copy AMI cross-region and replace
      InstanceType: t3.micro # TODO: match source instance type
      SubnetId: !Select [0, !Ref TargetSubnetIds]
      Tags:
        - Key: Name
          Value: ${action.resourceName}-migrated
        - Key: MigrationSource
          Value: ${action.resourceId}`;
}

function generateRdsResource(id: string, action: MigrationAction, req: MigrationRequirements): string {
  return `  ${id}:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Snapshot
    Properties:
      # For SNAPSHOT_RESTORE: use DBSnapshotIdentifier with the copied snapshot ARN
      # DBSnapshotIdentifier: 'arn:aws:rds:${req.targetRegion}:${req.targetAccountId}:snapshot:PLACEHOLDER'
      DBInstanceClass: db.t3.micro # TODO: match source
      Engine: postgres # TODO: match source engine
      MasterUsername: admin
      MasterUserPassword: !Ref DBPassword # Add as parameter
      VPCSecurityGroups:
        - !Ref TargetVpcId # TODO: reference actual SG
      Tags:
        - Key: Name
          Value: ${action.resourceName}-migrated
        - Key: MigrationSource
          Value: ${action.resourceId}`;
}

function generateS3Resource(id: string, action: MigrationAction): string {
  return `  ${id}:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub '\${Environment}-${action.resourceName.toLowerCase().replace(/[^a-z0-9-]/g, '-')}-migrated'
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: MigrationSource
          Value: ${action.resourceId}`;
}

function generateLambdaResource(id: string, action: MigrationAction): string {
  return `  ${id}:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ${action.resourceName}-migrated
      Runtime: python3.12 # TODO: match source runtime
      Handler: index.handler
      Code:
        S3Bucket: 'PLACEHOLDER' # TODO: deploy package to target region
        S3Key: 'PLACEHOLDER'
      Role: !Sub 'arn:aws:iam::\${AWS::AccountId}:role/lambda-execution-role' # TODO: create role
      Tags:
        - Key: MigrationSource
          Value: ${action.resourceId}`;
}

function generateDynamoDbResource(id: string, action: MigrationAction): string {
  return `  ${id}:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: ${action.resourceName}-migrated
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      Tags:
        - Key: MigrationSource
          Value: ${action.resourceId}
      # TODO: match source table schema (GSIs, LSIs, etc.)`;
}

function generateEcsClusterResource(id: string, action: MigrationAction): string {
  return `  ${id}:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: ${action.resourceName}-migrated
      CapacityProviders:
        - FARGATE
        - FARGATE_SPOT
      Tags:
        - Key: MigrationSource
          Value: ${action.resourceId}`;
}

function generateSqsResource(id: string, action: MigrationAction): string {
  return `  ${id}:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${action.resourceName}-migrated
      VisibilityTimeout: 30
      Tags:
        - Key: MigrationSource
          Value: ${action.resourceId}`;
}

function generateSnsResource(id: string, action: MigrationAction): string {
  return `  ${id}:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: ${action.resourceName}-migrated
      Tags:
        - Key: MigrationSource
          Value: ${action.resourceId}`;
}

function generateGenericResource(id: string, action: MigrationAction, cfnType: string): string {
  return `  ${id}:
    Type: ${cfnType}
    Properties:
      Tags:
        - Key: Name
          Value: ${action.resourceName}-migrated
        - Key: MigrationSource
          Value: ${action.resourceId}
      # TODO: configure properties for ${cfnType}`;
}

function generateManualPhaseTemplate(phase: MigrationPlanPhase, _req: MigrationRequirements): string {
  const steps = phase.actions.map((a, i) =>
    `#   ${i + 1}. ${a.description}\n#      Validation: ${a.validationSteps.join(', ')}`
  ).join('\n');

  return `AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  Migration Phase ${phase.order}: ${phase.name} (MANUAL STEPS - no CFN resources)
  This phase requires manual intervention. Follow the steps below.

# ═══════════════════════════════════════════════════════════════════
# MANUAL STEPS for Phase ${phase.order}: ${phase.name}
# ═══════════════════════════════════════════════════════════════════
#
${steps}
#
# ═══════════════════════════════════════════════════════════════════

Resources:
  # Placeholder - CFN requires at least one resource
  WaitConditionHandle:
    Type: AWS::CloudFormation::WaitConditionHandle

Outputs:
  PhaseStatus:
    Description: Manual phase - verify steps above are complete
    Value: 'MANUAL_STEPS_REQUIRED'
`;
}

// ── Output generators ────────────────────────────────────────────────────────

function generateOutputBlock(action: MigrationAction): string {
  const id = sanitizeLogicalId(action.resourceName || action.resourceId);
  return `  ${id}Output:
    Description: '${action.resourceType} - ${action.resourceName}'
    Value: !Ref ${id}
    Export:
      Name: !Sub '\${AWS::StackName}-${id}'`;
}

// ── Helpers ──────────────────────────────────────────────────────────────────

function sanitizeLogicalId(name: string): string {
  // CFN logical IDs: alphanumeric only, start with letter
  return name
    .replace(/[^a-zA-Z0-9]/g, '')
    .replace(/^[^a-zA-Z]/, 'R')
    .slice(0, 64) || 'Resource';
}
