import {
  CloudFormationClient,
  CreateGeneratedTemplateCommand,
  DescribeGeneratedTemplateCommand,
  GetGeneratedTemplateCommand,
  DeleteGeneratedTemplateCommand,
} from '@aws-sdk/client-cloudformation';
import type { ResourceType } from '../resources/resource.js';
import { logger } from '../../infrastructure/aws/logger.js';

/**
 * IaC Generator Engine — produces FAITHFUL CloudFormation.
 *
 * Instead of hand-rolling CFN from guessed properties, this uses the AWS
 * CloudFormation IaC Generator (launched 2024). It reads the REAL configuration
 * of existing resources (backed by AWS Config) and produces a CloudFormation
 * template that faithfully reproduces them — SG rules, UserData, metadata
 * options, block device mappings, everything.
 *
 * Flow: create-generated-template -> poll until COMPLETE -> get-generated-template
 *
 * The generated template is METADATA ONLY (creates no AWS resources). It is
 * deleted after we fetch the YAML. No cost. Read-only against the account.
 */

/** Maps our ResourceType to the CFN IaC Generator's resource identifier key. */
const RESOURCE_IDENTIFIER_KEY: Partial<Record<ResourceType, string>> = {
  'AWS::EC2::VPC': 'VpcId',
  'AWS::EC2::Subnet': 'SubnetId',
  'AWS::EC2::SecurityGroup': 'Id',
  'AWS::EC2::Instance': 'InstanceId',
  'AWS::EC2::InternetGateway': 'InternetGatewayId',
  'AWS::EC2::NatGateway': 'NatGatewayId',
  'AWS::EC2::RouteTable': 'RouteTableId',
  'AWS::EC2::Volume': 'VolumeId',
  'AWS::ECS::Cluster': 'ClusterName',
  'AWS::ECS::Service': 'ServiceArn',
  'AWS::ElasticLoadBalancingV2::LoadBalancer': 'LoadBalancerArn',
  'AWS::ElasticLoadBalancingV2::TargetGroup': 'TargetGroupArn',
  'AWS::RDS::DBInstance': 'DBInstanceIdentifier',
  'AWS::RDS::DBCluster': 'DBClusterIdentifier',
  'AWS::S3::Bucket': 'BucketName',
  'AWS::Lambda::Function': 'FunctionName',
  'AWS::IAM::Role': 'RoleName',
  'AWS::DynamoDB::Table': 'TableName',
  'AWS::SQS::Queue': 'QueueUrl',
  'AWS::SNS::Topic': 'TopicArn',
  'AWS::ECR::Repository': 'RepositoryName',
};

export interface ResourceToGenerate {
  resourceType: ResourceType;
  /** The physical resource ID (InstanceId, BucketName, etc.) */
  physicalId: string;
}

export interface FaithfulTemplateResult {
  status: 'COMPLETE' | 'FAILED' | 'PARTIAL';
  /** The faithful CloudFormation YAML (as generated by AWS) */
  templateBody: string;
  /** Resources that could NOT be captured by the generator */
  unresolvedResources: Array<{ resourceType: string; physicalId: string; reason: string }>;
  /** Warnings from the generation */
  warnings: string[];
}

export interface IacGeneratorOptions {
  region: string;
  /** Polling timeout in ms (default 120s) */
  timeoutMs?: number;
}

/**
 * Generate a faithful CloudFormation template for the given resources.
 * The template is fetched then the generated-template metadata is deleted.
 */
export async function generateFaithfulTemplate(
  resources: ResourceToGenerate[],
  options: IacGeneratorOptions
): Promise<FaithfulTemplateResult> {
  const client = new CloudFormationClient({ region: options.region });
  const templateName = `migration-${Date.now()}`;
  const timeoutMs = options.timeoutMs ?? 120_000;
  const warnings: string[] = [];
  const unresolved: FaithfulTemplateResult['unresolvedResources'] = [];

  // Build the resource list for the generator
  const cfnResources = resources
    .map(r => {
      const key = RESOURCE_IDENTIFIER_KEY[r.resourceType];
      if (!key) {
        unresolved.push({
          resourceType: r.resourceType,
          physicalId: r.physicalId,
          reason: 'ResourceType not supported by IaC Generator identifier mapping',
        });
        return null;
      }
      return {
        ResourceType: r.resourceType,
        ResourceIdentifier: { [key]: r.physicalId },
      };
    })
    .filter((r): r is NonNullable<typeof r> => r !== null);

  if (cfnResources.length === 0) {
    return {
      status: 'FAILED',
      templateBody: '',
      unresolvedResources: unresolved,
      warnings: ['No resources could be mapped to IaC Generator identifiers'],
    };
  }

  try {
    // 1. Create the generated template
    await client.send(new CreateGeneratedTemplateCommand({
      GeneratedTemplateName: templateName,
      Resources: cfnResources,
    }));
    logger.info('IaC Generator template created', { templateName, resourceCount: cfnResources.length });

    // 2. Poll until COMPLETE or FAILED
    const start = Date.now();
    let status = 'CREATE_PENDING';
    while (Date.now() - start < timeoutMs) {
      await new Promise(r => setTimeout(r, 3000));
      const desc = await client.send(new DescribeGeneratedTemplateCommand({
        GeneratedTemplateName: templateName,
      }));
      status = desc.Status ?? 'UNKNOWN';

      // Collect per-resource status (some may fail while others succeed)
      for (const rs of desc.Resources ?? []) {
        if (rs.ResourceStatus === 'FAILED') {
          unresolved.push({
            resourceType: rs.ResourceType ?? 'unknown',
            physicalId: JSON.stringify(rs.ResourceIdentifier ?? {}),
            reason: rs.ResourceStatusReason ?? 'Generation failed',
          });
        }
      }

      if (status === 'COMPLETE' || status === 'FAILED') break;
    }

    if (status !== 'COMPLETE' && status !== 'FAILED') {
      await cleanup(client, templateName);
      return {
        status: 'FAILED',
        templateBody: '',
        unresolvedResources: unresolved,
        warnings: [`IaC Generator timed out after ${timeoutMs}ms (status: ${status})`],
      };
    }

    // 3. Fetch the faithful template
    const tpl = await client.send(new GetGeneratedTemplateCommand({
      GeneratedTemplateName: templateName,
      Format: 'YAML',
    }));
    const templateBody = tpl.TemplateBody ?? '';

    // 4. Cleanup (delete the generated-template metadata)
    await cleanup(client, templateName);

    return {
      status: unresolved.length > 0 ? 'PARTIAL' : 'COMPLETE',
      templateBody,
      unresolvedResources: unresolved,
      warnings,
    };
  } catch (err) {
    await cleanup(client, templateName);
    const message = err instanceof Error ? err.message : String(err);
    logger.error('IaC Generator failed', { error: message });
    return {
      status: 'FAILED',
      templateBody: '',
      unresolvedResources: unresolved,
      warnings: [`IaC Generator error: ${message}`],
    };
  }
}

async function cleanup(client: CloudFormationClient, templateName: string): Promise<void> {
  try {
    await client.send(new DeleteGeneratedTemplateCommand({ GeneratedTemplateName: templateName }));
  } catch {
    // Best-effort cleanup — the generated template is metadata only, no cost
  }
}

/** Whether a resource type can be handled by the IaC Generator. */
export function isIacGeneratorSupported(resourceType: ResourceType): boolean {
  return resourceType in RESOURCE_IDENTIFIER_KEY;
}

/**
 * Adapt a faithful template for the TARGET region/account.
 *
 * The IaC Generator template hardcodes source-region physical IDs (VpcId,
 * SubnetId, SecurityGroup IDs, ImageId, private IPs). Those do not exist in the
 * target. This turns them into CloudFormation Parameters so the execution phase
 * can wire in the new IDs (from the networking stack) and the copied AMI/snapshot.
 *
 * Returns the adapted YAML plus the list of parameters that must be supplied at
 * deploy time.
 */
export interface AdaptedTemplate {
  yaml: string;
  requiredParameters: Array<{ name: string; description: string; sourceValue: string }>;
  removedAttributes: string[];
}

export function adaptForTarget(
  templateBody: string,
  opts: { targetRegion: string; targetAccountId?: string }
): AdaptedTemplate {
  const requiredParameters: AdaptedTemplate['requiredParameters'] = [];
  const removedAttributes: string[] = [];
  let yaml = templateBody;

  // Tag the template with the target destination for traceability
  const dest = opts.targetAccountId
    ? `${opts.targetRegion} (account ${opts.targetAccountId})`
    : opts.targetRegion;
  yaml = `# Adapted for target: ${dest}\n${yaml}`;

  // Patterns of source-region/account-specific values that must be parameterized.
  const patterns: Array<{ re: RegExp; param: string; desc: string }> = [
    { re: /vpc-[0-9a-f]{8,}/g, param: 'TargetVpcId', desc: 'VPC ID in the target region (from the networking stack)' },
    { re: /subnet-[0-9a-f]{8,}/g, param: 'TargetSubnetId', desc: 'Subnet ID in the target region' },
    { re: /sg-[0-9a-f]{8,}/g, param: 'TargetSecurityGroupId', desc: 'Security Group ID in the target region' },
    { re: /ami-[0-9a-f]{8,}/g, param: 'TargetImageId', desc: 'AMI ID copied to the target region' },
    { re: /snap-[0-9a-f]{8,}/g, param: 'TargetSnapshotId', desc: 'Snapshot ID copied to the target region' },
  ];

  for (const { re, param, desc } of patterns) {
    const matches = [...new Set(yaml.match(re) ?? [])];
    if (matches.length === 1) {
      // Single value → one parameter, replace with !Ref
      requiredParameters.push({ name: param, description: desc, sourceValue: matches[0]! });
      yaml = yaml.replace(re, `!Ref ${param}`);
    } else if (matches.length > 1) {
      // Multiple distinct values → parameterize each with a suffix
      matches.forEach((val, i) => {
        const p = `${param}${i + 1}`;
        requiredParameters.push({ name: p, description: `${desc} (${val})`, sourceValue: val });
        yaml = yaml.split(val).join(`!Ref ${p}`);
      });
    }
  }

  // Remove hardcoded private IPs (target subnet has a different CIDR)
  yaml = yaml.replace(/^\s*PrivateIpAddress:.*$/gm, (m) => {
    removedAttributes.push(m.trim());
    return '';
  });

  // Inject the Parameters block if we added any
  if (requiredParameters.length > 0) {
    const paramBlock = requiredParameters
      .map(p => `  ${p.name}:\n    Type: "String"\n    Description: "${p.description}"`)
      .join('\n');
    if (/^Parameters:/m.test(yaml)) {
      yaml = yaml.replace(/^Parameters:\s*$/m, `Parameters:\n${paramBlock}`);
    } else {
      // Insert Parameters after the AWSToolsMetrics/Metadata or at the top
      yaml = yaml.replace(/^(Resources:)/m, `Parameters:\n${paramBlock}\n$1`);
    }
  }

  return { yaml, requiredParameters, removedAttributes };
}
